2024-08-18 05:31:01,579 INFO    MainThread:40792 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2024-08-18 05:31:01,580 INFO    MainThread:40792 [wandb_setup.py:_flush():76] Configure stats pid to 40792
2024-08-18 05:31:01,580 INFO    MainThread:40792 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Zain_\.config\wandb\settings
2024-08-18 05:31:01,580 INFO    MainThread:40792 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Zain_\Dropbox\Personal\Data Science Projects\OpenAI_API_Fine_Tuning\wandb\settings
2024-08-18 05:31:01,580 INFO    MainThread:40792 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'notebook_name': 'fine_tune_openai_sentiment_wandb.ipynb'}
2024-08-18 05:31:01,580 INFO    MainThread:40792 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-08-18 05:31:01,580 INFO    MainThread:40792 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-08-18 05:31:01,580 INFO    MainThread:40792 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-18 05:31:01,580 INFO    MainThread:40792 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\Zain_\Dropbox\Personal\Data Science Projects\OpenAI_API_Fine_Tuning\wandb\run-20240818_053101-9807l04h\logs\debug.log
2024-08-18 05:31:01,580 INFO    MainThread:40792 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\Zain_\Dropbox\Personal\Data Science Projects\OpenAI_API_Fine_Tuning\wandb\run-20240818_053101-9807l04h\logs\debug-internal.log
2024-08-18 05:31:01,581 INFO    MainThread:40792 [wandb_init.py:init():607] calling init triggers
2024-08-18 05:31:01,581 INFO    MainThread:40792 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-08-18 05:31:01,581 INFO    MainThread:40792 [wandb_init.py:init():632] re-initializing run, found existing run on stack: kse879k8
2024-08-18 05:31:01,582 INFO    MainThread:40792 [wandb_run.py:_finish():2154] finishing run suspicious-cow-self/Reddit_Sentiment_Analysis/kse879k8
2024-08-18 05:31:01,684 INFO    MainThread:40792 [jupyter.py:save_history():444] not saving jupyter history
2024-08-18 05:31:01,685 INFO    MainThread:40792 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-08-18 05:31:01,685 INFO    MainThread:40792 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2024-08-18 05:31:01,685 INFO    MainThread:40792 [wandb_run.py:_atexit_cleanup():2418] got exitcode: 0
2024-08-18 05:31:01,685 INFO    MainThread:40792 [wandb_run.py:_restore():2400] restore
2024-08-18 05:31:01,685 INFO    MainThread:40792 [wandb_run.py:_restore():2406] restore done
